In [1]:
#Decision Tree-used for categorical data as well as numerical data but most preferred for categorical data

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [3]:
cars_data=pd.read_csv('cars.csv',header=None)

cars_data.head()

0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

In [4]:
print(cars_data.shape)

(1728, 7)


In [5]:
cars_data.columns=['buying','maint','doors','persons','lug_boot','safety','classes']

In [6]:
cars_data.head()

buying  maint doors persons lug_boot safety classes
0  vhigh  vhigh     2       2    small    low   unacc
1  vhigh  vhigh     2       2    small    med   unacc
2  vhigh  vhigh     2       2    small   high   unacc
3  vhigh  vhigh     2       2      med    low   unacc
4  vhigh  vhigh     2       2      med    med   unacc

In [7]:
#Check that is there any null or missing values in the dataset
cars_data.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [8]:
cars_df=pd.DataFrame(cars_data)

In [9]:
cars_df.head()

buying  maint doors persons lug_boot safety classes
0  vhigh  vhigh     2       2    small    low   unacc
1  vhigh  vhigh     2       2    small    med   unacc
2  vhigh  vhigh     2       2    small   high   unacc
3  vhigh  vhigh     2       2      med    low   unacc
4  vhigh  vhigh     2       2      med    med   unacc

In [10]:
#Converting Categorical data into numerical using LabelEncoder
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

for x in cars_df.columns:
    cars_df[x]=le.fit_transform(cars_df[x])

In [11]:
#After transforming 
cars_df.head()


buying  maint  doors  persons  lug_boot  safety  classes
0       3      3      0        0         2       1        2
1       3      3      0        0         2       2        2
2       3      3      0        0         2       0        2
3       3      3      0        0         1       1        2
4       3      3      0        0         1       2        2

In [12]:
cars_df.classes.value_counts()

#acc==>0
#good==>1
#unacc==>2
#vgood==>3

2    1210
0     384
1      69
3      65
Name: classes, dtype: int64

In [13]:
X=cars_df.values[:,:-1]
Y=cars_df.values[:,-1]
Y=Y.astype(int)

In [14]:
#It doesn't matter to Scale data here but it is a good practice to Scale a data
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

scaler.fit(X)
X=scaler.transform(X)

#If you have 2 different file then-->Fit always perform on training data and transform on both training and testing data

In [15]:
print(X)

[[ 1.34164079  1.34164079 -1.34164079 -1.22474487  1.22474487  0.        ]
 [ 1.34164079  1.34164079 -1.34164079 -1.22474487  1.22474487  1.22474487]
 [ 1.34164079  1.34164079 -1.34164079 -1.22474487  1.22474487 -1.22474487]
 ...
 [-0.4472136  -0.4472136   1.34164079  1.22474487 -1.22474487  0.        ]
 [-0.4472136  -0.4472136   1.34164079  1.22474487 -1.22474487  1.22474487]
 [-0.4472136  -0.4472136   1.34164079  1.22474487 -1.22474487 -1.22474487]]


In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=10)  
#Bydefault test-size is 0.25
#I prefer 80-20 split when observation less than 1k and 70-30 when observation is larger than 1k

### Running Decision Tree Model

In [17]:
from sklearn.tree import DecisionTreeClassifier
model_DecisionTree=DecisionTreeClassifier(criterion='gini',random_state=10)

#fit the model on the data and predict the values
model_DecisionTree.fit(X_train,Y_train)

#Predict
Y_pred=model_DecisionTree.predict(X_test)
print(Y_pred)

[2 2 2 2 1 2 0 0 2 0 2 2 2 2 0 0 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 0 2 2 2
 2 2 0 2 2 2 3 2 0 2 2 2 2 2 0 1 3 1 2 0 2 0 2 2 2 2 3 2 2 0 0 2 2 3 2 2 2
 1 2 0 0 2 2 2 2 2 2 2 2 2 0 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2
 2 2 2 0 2 2 1 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 0 2 2 3 2 2 0 2 0 3 2 2 2 2
 2 2 2 2 3 2 2 2 2 2 1 1 2 0 2 2 2 2 2 2 2 2 2 1 2 3 2 2 2 2 0 0 2 2 2 2 3
 2 0 2 1 0 2 2 2 2 0 3 0 0 2 2 2 2 0 2 2 2 2 2 2 2 3 0 2 2 2 3 2 2 1 2 2 2
 2 2 2 2 0 2 2 2 2 2 0 0 2 2 2 2 3 2 2 0 2 0 2 0 2 2 2 2 2 0 2 2 2 0 2 2 0
 2 2 2 0 2 2 2 0 2 2 0 2 2 2 1 1 2 2 2 0 2 2 0 3 3 0 2 0 2 2 2 3 2 2 0 2 2
 2 2 2 0 2 2 2 3 2 2 2 0 2 2 2 2 0 0 2 2 1 2 2 2 0 2 2 0 0 2 0 0 2 2 0 0 2
 2 2 2 2 0 2 2 2 0 2 2 2 2 2 2 2 2 1 3 3 2 2 2 2 0 2 2 2 3 2 2 0 2 1 2 2 2
 0 0 2 2 2 2 2 2 2 0 2 0 1 2 2 2 2 2 0 2 2 3 0 0 0 0 2 0 2 2 2 0 0 2 0 2 1
 0 2 2 0 2 2 2 0 1 2 0 0 2 0 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 3 2 2 2 2 0 2 2
 2 0 2 2 2 0 2 2 2 0 2 2 0 3 2 2 2 2 0 2 2 2 2 2 2 0 2 0 2 0 2 2 2 2 0 2 2
 2 2 2 2 2 2 2 1 2 2 2 2 

In [18]:
#Comparing actual vs predict
print(list(zip(Y_test,Y_pred)))

[(2, 2), (2, 2), (2, 2), (2, 2), (1, 1), (2, 2), (0, 0), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (3, 3), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (1, 1), (3, 3), (1, 1), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (3, 3), (2, 2), (2, 2), (0, 0), (0, 0), (2, 2), (2, 2), (3, 3), (2, 2), (2, 2), (2, 2), (1, 1), (2, 2), (0, 0), (3, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (1, 1), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0),

In [19]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[101   0   1   0]
 [  2  19   0   0]
 [  0   0 371   0]
 [  1   0   0  24]]
0.9922928709055877
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       102
           1       1.00      0.90      0.95        21
           2       1.00      1.00      1.00       371
           3       1.00      0.96      0.98        25

    accuracy                           0.99       519
   macro avg       0.99      0.96      0.98       519
weighted avg       0.99      0.99      0.99       519



In [20]:
#Check accuracy of training data 
model_DecisionTree.score(X_train,Y_train)

1.0

In [21]:
#Checking accuracy of testing data(unseen data)
model_DecisionTree.score(X_test,Y_test)

0.9922928709055877

#### Here we conclude that our model is not overfitted because it is giving good accuracy on testing data as well.

In [22]:
print(model_DecisionTree.feature_importances_)  

#feature_importances-->tells us which feature is more important

[0.15108488 0.25065085 0.06002633 0.19355707 0.09892621 0.24575465]


In [36]:
#when working with more column data
print(list(zip(cars_df.columns[0:-1],model_DecisionTree.feature_importances_)))

[('buying', 0.1510848831946676), ('maint', 0.2506508516803624), ('doors', 0.060026331736828115), ('persons', 0.19355707150872045), ('lug_boot', 0.09892620952419463), ('safety', 0.2457546523552268)]


In [38]:
from sklearn import tree
with open("model_DecisionTree.txt",'w')as f:
    
    f=tree.export_graphviz(model_DecisionTree,feature_names=cars_df.columns[:-1],out_file=f)
    
#generate the file and upload the code in webgraphviz.com to plot the decision tree

### Pruning


In [23]:
from sklearn.tree import DecisionTreeClassifier
model_DecisionTree=DecisionTreeClassifier(criterion='gini',max_depth=10,min_samples_leaf=5,max_leaf_nodes=300,random_state=10)

#fit the data on the model and predict the values
model_DecisionTree.fit(X_train,Y_train)
Y_pred=model_DecisionTree.predict(X_test)
print(Y_pred)

[2 2 2 2 1 2 0 0 2 0 2 2 2 2 0 0 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 0 2 2 2
 2 2 0 2 2 2 1 2 0 2 2 2 2 2 0 1 3 1 2 0 2 0 2 2 2 2 0 2 2 1 0 2 2 3 2 2 2
 1 2 0 0 2 2 2 2 2 2 2 2 2 0 2 0 2 2 2 0 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2
 2 2 2 1 2 2 1 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 0 2 2 3 2 2 0 2 0 3 2 2 2 2
 2 2 2 2 3 0 2 2 2 2 1 1 2 0 2 2 2 2 2 2 2 2 2 1 0 3 2 2 2 2 0 0 2 2 2 2 3
 2 0 2 1 0 2 2 2 2 0 3 0 0 2 2 2 2 0 2 0 2 2 0 2 2 1 0 0 2 2 0 2 2 1 2 2 2
 2 2 2 2 0 2 2 2 2 2 0 0 2 2 2 2 3 2 2 0 2 0 2 0 2 2 2 2 2 0 2 2 2 0 2 2 0
 2 2 2 0 2 2 2 0 2 2 0 2 2 2 1 1 2 2 2 0 2 2 0 3 3 0 0 0 2 2 2 3 2 2 0 2 2
 2 2 2 0 2 2 2 1 2 2 2 0 2 2 2 2 0 0 2 2 1 2 2 2 0 2 2 0 0 2 0 0 2 2 2 0 2
 2 2 2 2 0 2 2 2 0 2 2 2 2 2 2 2 2 1 1 3 2 2 2 2 0 2 2 2 3 2 2 2 2 1 2 2 2
 0 0 2 2 2 2 2 2 2 0 2 0 1 2 2 2 2 2 0 2 2 3 2 0 0 0 2 1 2 2 2 0 1 2 0 2 3
 0 2 2 0 2 2 2 0 1 2 0 0 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 2 2 2 2 0 2 2
 2 0 2 2 2 0 2 2 2 0 2 2 0 1 2 2 2 2 3 2 2 2 2 2 2 0 2 0 2 0 2 2 2 2 0 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 

In [24]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))

[[ 92   6   4   0]
 [  0  17   2   2]
 [  8   0 363   0]
 [  3   5   0  17]]
              precision    recall  f1-score   support

           0       0.89      0.90      0.90       102
           1       0.61      0.81      0.69        21
           2       0.98      0.98      0.98       371
           3       0.89      0.68      0.77        25

    accuracy                           0.94       519
   macro avg       0.84      0.84      0.84       519
weighted avg       0.95      0.94      0.94       519

0.9421965317919075


In [25]:
#Check accuracy of training data 
model_DecisionTree.score(X_train,Y_train)

0.9652605459057072

In [26]:
#Checking accuracy of testing data(unseen data)
model_DecisionTree.score(X_test,Y_test)

0.9421965317919075

#### Earlier we were getting very good score and now after pruning it decreases-so unneccessarily we should not prune the tree

### Base SVM

In [34]:
from sklearn import svm
classifier=svm.SVC(kernel="rbf",gamma=0.1,C=1)

#fitting traing data to the model
classifier.fit(X_train,Y_train)

Y_pred=classifier.predict(X_test)
print(Y_pred)

[2 2 2 2 0 2 0 0 2 0 2 2 2 2 0 0 2 2 2 2 2 2 0 2 2 2 2 0 2 2 2 2 2 2 2 2 2
 2 2 0 2 2 2 0 0 0 2 2 2 2 2 0 0 3 0 2 2 2 0 2 2 2 2 0 2 2 0 0 2 2 0 2 2 2
 0 2 0 0 2 2 0 2 0 2 2 2 2 0 2 0 2 2 2 0 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2
 2 2 2 2 2 2 0 2 2 2 2 2 2 0 2 2 2 2 2 2 0 2 2 0 2 2 3 2 2 2 2 0 3 2 2 2 2
 2 2 2 2 0 2 2 2 2 2 0 0 2 0 2 2 2 2 2 2 2 2 2 0 2 0 2 2 2 2 0 0 0 2 2 2 0
 2 2 2 0 0 0 2 2 2 0 3 2 0 2 2 2 2 0 2 2 2 2 2 2 2 0 0 2 2 2 0 2 2 0 2 0 2
 2 2 2 2 0 2 2 2 2 2 0 0 2 2 2 2 3 2 2 2 2 0 2 0 2 2 2 2 2 0 2 2 2 2 2 2 0
 2 2 2 0 2 2 2 0 2 2 0 2 2 2 0 0 2 2 2 0 0 2 0 3 0 0 0 2 2 2 2 3 2 2 2 2 2
 2 2 2 0 2 2 2 0 2 0 2 0 2 2 2 2 2 0 2 2 0 2 2 2 0 2 2 0 0 2 0 0 2 0 2 0 2
 2 2 2 2 0 2 2 2 0 2 2 2 2 2 2 2 2 0 0 0 2 2 2 2 0 2 2 2 3 2 2 0 2 0 2 2 2
 0 0 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 0 2 0 0 0 2 0 2 2 2 0 0 2 0 2 0
 0 2 2 0 2 2 2 0 0 2 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2
 2 0 2 2 2 0 2 2 2 0 2 2 2 0 2 2 2 0 0 2 2 2 2 2 2 0 2 0 2 0 2 2 2 2 0 0 0
 2 2 0 2 2 2 2 0 2 2 2 2 

In [35]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))

[[ 82   0  20   0]
 [ 21   0   0   0]
 [ 17   0 354   0]
 [ 17   0   0   8]]
              precision    recall  f1-score   support

           0       0.60      0.80      0.69       102
           1       0.00      0.00      0.00        21
           2       0.95      0.95      0.95       371
           3       1.00      0.32      0.48        25

    accuracy                           0.86       519
   macro avg       0.64      0.52      0.53       519
weighted avg       0.84      0.86      0.84       519

0.8554913294797688


C:\Users\Pradeepkumar Verma\updated anaconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Pradeepkumar Verma\updated anaconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Pradeepkumar Verma\updated anaconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(resu

### SVM Tuning

In [36]:
from sklearn import svm
classifier=svm.SVC(kernel="rbf",gamma=0.1,C=50)

#fitting traing data to the model
classifier.fit(X_train,Y_train)

Y_pred=classifier.predict(X_test)
#print(Y_pred)

In [32]:
print(list(zip(Y_test,Y_pred)))

[(2, 2), (2, 2), (2, 2), (2, 2), (1, 1), (2, 2), (0, 0), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (3, 3), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (1, 1), (3, 3), (1, 1), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (3, 3), (2, 2), (2, 2), (0, 0), (0, 0), (2, 2), (2, 2), (3, 3), (2, 2), (2, 2), (2, 2), (1, 1), (2, 2), (0, 0), (3, 3), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (1, 1), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 1),

In [33]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))

[[100   1   1   0]
 [  0  21   0   0]
 [  0   0 371   0]
 [  0   0   0  25]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       102
           1       0.95      1.00      0.98        21
           2       1.00      1.00      1.00       371
           3       1.00      1.00      1.00        25

    accuracy                           1.00       519
   macro avg       0.99      1.00      0.99       519
weighted avg       1.00      1.00      1.00       519

0.9961464354527938


### Base KNN

In [38]:
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=8,metric='euclidean')

#fit the data on the model and predict the values
model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)
#print(Y_pred)

In [39]:
print(list(zip(Y_test,Y_pred)))

[(2, 2), (2, 2), (2, 2), (2, 2), (1, 1), (2, 2), (0, 0), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (3, 3), (2, 0), (0, 0), (2, 2), (2, 0), (2, 2), (2, 2), (2, 2), (0, 0), (1, 1), (3, 3), (1, 1), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (3, 0), (2, 2), (2, 2), (0, 0), (0, 0), (2, 2), (2, 2), (3, 3), (2, 2), (2, 2), (2, 2), (1, 1), (2, 2), (0, 0), (3, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 0), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (1, 1), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 2),

In [40]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))

[[ 98   0   4   0]
 [  7  13   0   1]
 [ 12   0 359   0]
 [  4   0   0  21]]
              precision    recall  f1-score   support

           0       0.81      0.96      0.88       102
           1       1.00      0.62      0.76        21
           2       0.99      0.97      0.98       371
           3       0.95      0.84      0.89        25

    accuracy                           0.95       519
   macro avg       0.94      0.85      0.88       519
weighted avg       0.95      0.95      0.95       519

0.9460500963391136


### KNN by using sqrt

In [42]:
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=34,metric='euclidean')

#fit the data on the model and predict the values
model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)
#print(Y_pred)

In [41]:
int(np.sqrt(len(X_train)))

34

In [43]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))

[[ 47   0  55   0]
 [ 16   0   5   0]
 [  4   0 367   0]
 [ 10   0   7   8]]
              precision    recall  f1-score   support

           0       0.61      0.46      0.53       102
           1       0.00      0.00      0.00        21
           2       0.85      0.99      0.91       371
           3       1.00      0.32      0.48        25

    accuracy                           0.81       519
   macro avg       0.61      0.44      0.48       519
weighted avg       0.77      0.81      0.78       519

0.8131021194605009


C:\Users\Pradeepkumar Verma\updated anaconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Pradeepkumar Verma\updated anaconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Pradeepkumar Verma\updated anaconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(resu

### Logistic Regression

In [44]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()

#fitting the data to the model and predict the values
lr.fit(X_train,Y_train)
Y_pred=lr.predict(X_test)
#print(Y_pred)


In [45]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))

[[ 19   0  78   5]
 [  3   0  18   0]
 [ 30   0 339   2]
 [  8   0  14   3]]
              precision    recall  f1-score   support

           0       0.32      0.19      0.23       102
           1       0.00      0.00      0.00        21
           2       0.76      0.91      0.83       371
           3       0.30      0.12      0.17        25

    accuracy                           0.70       519
   macro avg       0.34      0.31      0.31       519
weighted avg       0.62      0.70      0.65       519

0.6955684007707129


C:\Users\Pradeepkumar Verma\updated anaconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Pradeepkumar Verma\updated anaconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Pradeepkumar Verma\updated anaconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(resu

In [ ]:
### Logistic Regression is not suitable for multiclass classification
## Decision tree,SVM,KNN are suitable for binary as well as multiclass classification

### Base DecisionTree model and Tuned SVM both are giving me approx same accuracy-But SVM requires a high training time and i had to tune SVM to reach this accuracy so we will deliver base DecisionTree model instead of complex SVM model.